import { GpuVfxFrameId } from './GpuVfxAtlas';
import { GpuVfxLaneId } from './GpuVfxRenderLanes';

/**
 * GpuVfxEffects – der Manifest der *logischen* Effekte.
 *
 * Ein Effekt ist die semantische Einheit: er traegt sein Motiv, seine Qualitaetsklasse, seinen
 * Source-Lifecycle und seine Zeile im Profiler-Report. Auf welchem physischen Layer er landet,
 * steht in `GpuVfxRenderLanes.ts` – mehrere Effekte duerfen sich eine Lane teilen, ohne dass ihre
 * Statistik zusammenfaellt.
 */

export const GpuVfxEffectId = {
  AirstrikeBomb:  0,
  AirstrikeSpark: 1,
  RocketExhaust:  2,
  RocketSmoke:    3,
  StinkInner:     4,
  StinkPlume:     5,
  StinkAccent:    6,
  StinkEdge:      7,
  FlameCore:      8,
  FlameOuter:     9,
  FlameSpark:     10,
  GroundFireOuter:    11,
  GroundFireCore:     12,
  GroundFireSpark:    13,
  GroundFireSmoke:    14,
  ProjectileBurnOuter: 15,
  ProjectileBurnCore:  16,
  ProjectileBurnSpark: 17,
  EntityBurnCore:     18,
  EntityBurnOuter:    19,
  EntityBurnSpark:    20,
  LeafDebris:         21,
  LeafBlowerDust:     22,
  GroundFireHeatBody:  23,
  ExplosionSpark:     24,
  ExplosionEmberDown: 25,
  ExplosionEmberUp:   26,
  ExplosionAccent:    27,
  ExplosionCascade:    28,
  ExplosionTrainChunk: 29,
  ExplosionTrainSpark: 30,
  ExplosionLightningSpark: 31,
  ExplosionHolyCrown:  32,
  ExplosionTrainCore:  33,
  ExplosionNukePlume:  34,
  ExplosionNukeFallout: 35,
  ExplosionRegeneration: 36,
  GroundFireEmber:    37,
  ExplosionBody:      38,
  ExplosionSmoke:     39,
  ExplosionShockwave: 40,
  ExplosionSecondary: 41,
  DeathFragment: 42,
  DeathMicroFragment: 43,
  DeathGlow: 44,
  BloodCore: 45,
  BloodStreak: 46,
  BloodDroplet: 47,
  BloodMicroDroplet: 48,
  PowerUpPedestalAmbient: 49,
  PowerUpPedestalSpark: 50,
  PowerUpPedestalBurst: 51,
  MuzzleFlashBody: 52,
  MuzzleFlashSpark: 53,
  DeathFragmentGlow: 54,
} as const;

export type GpuVfxEffectId = (typeof GpuVfxEffectId)[keyof typeof GpuVfxEffectId];

/** Dieselben Kategorien wie `GraphicsQualityProfile.particleFactors`. */
export type GpuVfxImportance = 'critical' | 'standard' | 'decorative';

/**
 * `kill-with-source`: verschwindet die Quelle, werden ihre lebenden Member sofort stillgelegt.
 * `linger`: die Quelle verschwindet, bereits gespawnte Member leben normal aus.
 */
export type GpuVfxReleaseMode = 'kill-with-source' | 'linger';

export interface GpuVfxEffectSpec {
  readonly id: GpuVfxEffectId;
  /** Zwei-Ebenen-Profiling: dieser Name steht im Report, auch bei geteilter Lane. */
  readonly label: string;
  readonly lane: GpuVfxLaneId;
  /** Nur fuer Effekte, die je nach Variante additiv zeichnen (Wolkenpartikel). */
  readonly laneAdditive?: GpuVfxLaneId;
  readonly frame: GpuVfxFrameId;
  readonly importance: GpuVfxImportance;
  readonly release: GpuVfxReleaseMode;
}

/** Reihenfolge = `GpuVfxEffectId`. */
export const GPU_VFX_EFFECTS: readonly GpuVfxEffectSpec[] = [
  {
    id: GpuVfxEffectId.AirstrikeBomb,
    label: 'airstrike.bomb',
    lane: GpuVfxLaneId.AirstrikeBomb,
    frame: GpuVfxFrameId.AirstrikeBomb,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.AirstrikeSpark,
    label: 'airstrike.spark',
    lane: GpuVfxLaneId.AirstrikeSpark,
    frame: GpuVfxFrameId.AirstrikeSpark,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.RocketExhaust,
    label: 'rocket.exhaust',
    lane: GpuVfxLaneId.RocketExhaust,
    frame: GpuVfxFrameId.RocketExhaust,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.RocketSmoke,
    label: 'rocket.smoke',
    lane: GpuVfxLaneId.RocketSmoke,
    frame: GpuVfxFrameId.RocketSmoke,
    importance: 'standard',
    // Beim Zerstoeren einer einzelnen Rakete liefen die Schwaden des geteilten Emitters aus,
    // statt zu verschwinden. Nur der Teardown raeumt sie ab.
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.StinkInner,
    label: 'stink.inner',
    lane: GpuVfxLaneId.StinkNormal,
    laneAdditive: GpuVfxLaneId.StinkAdd,
    frame: GpuVfxFrameId.StinkPuff,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.StinkPlume,
    label: 'stink.plume',
    lane: GpuVfxLaneId.StinkNormal,
    laneAdditive: GpuVfxLaneId.StinkAdd,
    frame: GpuVfxFrameId.StinkPuff,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.StinkAccent,
    label: 'stink.accent',
    lane: GpuVfxLaneId.StinkAdd,
    frame: GpuVfxFrameId.StinkPuff,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.StinkEdge,
    label: 'stink.edge',
    lane: GpuVfxLaneId.StinkAdd,
    frame: GpuVfxFrameId.StinkPuff,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.FlameCore,
    label: 'flame.core',
    lane: GpuVfxLaneId.FlameCore,
    frame: GpuVfxFrameId.FlameCore,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.FlameOuter,
    label: 'flame.outer',
    lane: GpuVfxLaneId.FlameOuter,
    frame: GpuVfxFrameId.FlameOuter,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.FlameSpark,
    label: 'flame.spark',
    lane: GpuVfxLaneId.FlameSpark,
    frame: GpuVfxFrameId.FlameSpark,
    importance: 'standard',
    release: 'kill-with-source',
  },
  // ── Bodenfeuer. Eine erloschene GroundFire-Quelle laesst ihre Partikel auslaufen; nur der
  //    Rundenteardown raeumt sie ab. Deshalb `linger` und eine einzige geteilte Quelle.
  {
    id: GpuVfxEffectId.GroundFireOuter,
    label: 'groundfire.outer',
    lane: GpuVfxLaneId.GroundFire,
    frame: GpuVfxFrameId.GroundFireSurface,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.GroundFireCore,
    label: 'groundfire.core',
    lane: GpuVfxLaneId.GroundFire,
    frame: GpuVfxFrameId.GroundFireSurface,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.GroundFireSpark,
    label: 'groundfire.spark',
    lane: GpuVfxLaneId.GroundFire,
    frame: GpuVfxFrameId.FlameSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.GroundFireSmoke,
    label: 'groundfire.smoke',
    lane: GpuVfxLaneId.GroundFireSmoke,
    frame: GpuVfxFrameId.GroundFireSmoke,
    importance: 'standard',
    release: 'linger',
  },
  // ── Trails brennender Projektile. Die Emitter waren schon bisher global geteilt; ein
  //    verschwindendes Projektil liess seinen Trail auslaufen.
  {
    id: GpuVfxEffectId.ProjectileBurnOuter,
    label: 'projburn.outer',
    lane: GpuVfxLaneId.ProjectileBurn,
    frame: GpuVfxFrameId.FlameOuter,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ProjectileBurnCore,
    label: 'projburn.core',
    lane: GpuVfxLaneId.ProjectileBurn,
    frame: GpuVfxFrameId.FlameCore,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ProjectileBurnSpark,
    label: 'projburn.spark',
    lane: GpuVfxLaneId.ProjectileBurn,
    frame: GpuVfxFrameId.FlameSpark,
    importance: 'standard',
    release: 'linger',
  },
  // ── Brennende Spieler und Gegner. `stop(true)` bzw. `destroy()` legten die Partikel bisher
  //    sofort still, sobald die Stacks fielen – das ist genau `kill-with-source`.
  {
    id: GpuVfxEffectId.EntityBurnCore,
    label: 'entityburn.core',
    lane: GpuVfxLaneId.EntityBurn,
    frame: GpuVfxFrameId.FlameCore,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.EntityBurnOuter,
    label: 'entityburn.outer',
    lane: GpuVfxLaneId.EntityBurn,
    frame: GpuVfxFrameId.FlameOuter,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.EntityBurnSpark,
    label: 'entityburn.spark',
    lane: GpuVfxLaneId.EntityBurn,
    frame: GpuVfxFrameId.FlameSpark,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.LeafDebris,
    label: 'leaf.debris',
    lane: GpuVfxLaneId.WorldDebris,
    frame: GpuVfxFrameId.LeafDebris,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.LeafBlowerDust,
    label: 'leafblower.dust',
    lane: GpuVfxLaneId.WorldDebris,
    frame: GpuVfxFrameId.LeafBlowerDust,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.GroundFireHeatBody,
    label: 'groundfire.heat-body',
    lane: GpuVfxLaneId.GroundFire,
    frame: GpuVfxFrameId.GroundFireBed,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionSpark,
    label: 'explosion.spark',
    lane: GpuVfxLaneId.ExplosionSpark,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionEmberDown,
    label: 'explosion.ember-down',
    lane: GpuVfxLaneId.ExplosionEmberDown,
    frame: GpuVfxFrameId.ExplosionEmber,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionEmberUp,
    label: 'explosion.ember-up',
    lane: GpuVfxLaneId.ExplosionEmberUp,
    frame: GpuVfxFrameId.ExplosionEmber,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionAccent,
    label: 'explosion.accent',
    lane: GpuVfxLaneId.ExplosionAccent,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionCascade,
    label: 'explosion.cascade',
    lane: GpuVfxLaneId.ExplosionCascade,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionTrainChunk,
    label: 'explosion.train-chunk',
    lane: GpuVfxLaneId.ExplosionTrainChunk,
    frame: GpuVfxFrameId.FlameOuter,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionTrainSpark,
    label: 'explosion.train-spark',
    lane: GpuVfxLaneId.ExplosionTrainSpark,
    frame: GpuVfxFrameId.FlameSpark,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionLightningSpark,
    label: 'explosion.lightning-spark',
    lane: GpuVfxLaneId.ExplosionTrainSpark,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionHolyCrown,
    label: 'explosion.holy-crown',
    lane: GpuVfxLaneId.ExplosionHolyCrown,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionTrainCore,
    label: 'explosion.train-core',
    lane: GpuVfxLaneId.ExplosionTrainCore,
    frame: GpuVfxFrameId.FlameCore,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionNukePlume,
    label: 'explosion.nuke-plume',
    lane: GpuVfxLaneId.ExplosionNukePlume,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionNukeFallout,
    label: 'explosion.nuke-fallout',
    lane: GpuVfxLaneId.ExplosionNukeFallout,
    frame: GpuVfxFrameId.ExplosionSmoke,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionRegeneration,
    label: 'explosion.regeneration',
    lane: GpuVfxLaneId.ExplosionRegeneration,
    frame: GpuVfxFrameId.ExplosionSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    // Die hellen Glutnester der Brandflaeche. Eigener Effekt statt einer Variante des Heissfelds:
    // sie tragen eine andere Lebensdauer und eine eigene Dichte, und der Profiler soll ihren
    // Anteil an der Lane getrennt ausweisen. Das Motiv ist dasselbe Wolkenfeld, nur klein.
    id: GpuVfxEffectId.GroundFireEmber,
    label: 'groundfire.ember',
    lane: GpuVfxLaneId.GroundFire,
    frame: GpuVfxFrameId.GroundFireSurface,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionBody,
    label: 'explosion.body',
    lane: GpuVfxLaneId.ExplosionEmberDown,
    frame: GpuVfxFrameId.ExplosionFireballA,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionSmoke,
    label: 'explosion.smoke',
    lane: GpuVfxLaneId.ExplosionSmoke,
    frame: GpuVfxFrameId.ExplosionSmoke,
    importance: 'decorative',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionShockwave,
    label: 'explosion.shockwave',
    lane: GpuVfxLaneId.ExplosionAccent,
    frame: GpuVfxFrameId.ExplosionRing,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.ExplosionSecondary,
    label: 'explosion.secondary',
    lane: GpuVfxLaneId.ExplosionEmberDown,
    frame: GpuVfxFrameId.ExplosionFireballB,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.DeathFragment,
    label: 'death.fragment',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.DeathFragment,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.DeathMicroFragment,
    label: 'death.micro-fragment',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.DeathDustMoteA,
    importance: 'decorative',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.DeathGlow,
    label: 'death.glow',
    lane: GpuVfxLaneId.GoreAdd,
    frame: GpuVfxFrameId.DeathGlow,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.BloodCore,
    label: 'blood.core',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.BloodStain,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.BloodStreak,
    label: 'blood.streak',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.BloodStreak,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.BloodDroplet,
    label: 'blood.droplet',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.BloodDroplet,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.BloodMicroDroplet,
    label: 'blood.micro-droplet',
    lane: GpuVfxLaneId.GoreNormal,
    frame: GpuVfxFrameId.BloodDroplet,
    importance: 'decorative',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.PowerUpPedestalAmbient,
    label: 'powerup.pedestal-ambient',
    lane: GpuVfxLaneId.PowerUpPedestal,
    frame: GpuVfxFrameId.DeathGlow,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.PowerUpPedestalSpark,
    label: 'powerup.pedestal-spark',
    lane: GpuVfxLaneId.PowerUpPedestal,
    frame: GpuVfxFrameId.DeathFragment,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.PowerUpPedestalBurst,
    label: 'powerup.pedestal-burst',
    lane: GpuVfxLaneId.PowerUpPedestal,
    frame: GpuVfxFrameId.DeathGlow,
    importance: 'standard',
    release: 'kill-with-source',
  },
  {
    id: GpuVfxEffectId.MuzzleFlashBody,
    label: 'muzzleFlash.body',
    lane: GpuVfxLaneId.MuzzleFlash,
    frame: GpuVfxFrameId.MuzzleFlash,
    importance: 'critical',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.MuzzleFlashSpark,
    label: 'muzzleFlash.spark',
    lane: GpuVfxLaneId.MuzzleFlash,
    frame: GpuVfxFrameId.MuzzleSpark,
    importance: 'standard',
    release: 'linger',
  },
  {
    id: GpuVfxEffectId.DeathFragmentGlow,
    label: 'death.fragment-glow',
    lane: GpuVfxLaneId.GoreAdd,
    frame: GpuVfxFrameId.DeathGlow,
    importance: 'standard',
    release: 'linger',
  },
];
