import {
  getStoredCoopDefenseLoadout,
  getStoredCoopDefenseProgress,
  addStoredCoopDefenseXp,
  claimStoredPendingCoopDefenseItemReward,
  equipStoredCoopDefenseItem,
  markStoredCoopDefenseItemsSeen,
  markStoredCoopDefenseBossMapCompleted,
  markStoredCoopDefenseRoundProcessed,
  resetStoredCoopDefenseCharacter,
  resetStoredCoopDefenseUpgradeProfiles,
  restoreStoredCoopDefenseProgress,
  salvageStoredCoopDefenseItem,
  setStoredPersistentBaseAreaStage,
  setStoredPersistentBaseUnlocked,
  grantStoredPersistentBaseRewards,
  setStoredCoopDefenseCheatProgress,
  setStoredCoopDefenseItemsUnlocked,
  setStoredCoopDefenseLoadoutSlot,
  setStoredPendingCoopDefenseItemReward,
  setStoredCoopDefenseUpgradeProfile,
  setStoredLoadoutSlot,
  switchStoredCoopDefenseClassLoadout,
  unequipStoredCoopDefenseItem,
  unlockStoredCoopDefenseClassesAfterVictory,
  unlockStoredCoopDefenseMapAfterVictory,
  unlockStoredCoopDefenseItemsAfterVictory,
  unlockStoredPersistentBaseAfterVictory,
  unlockStoredPersistentBaseAreaStageAfterVictory,
} from '../../utils/localPreferences';
import type { ArenaMetaProgressStore } from './ArenaMetaController';

/**
 * Adapter fuer den persoenlichen Meta-Stand. Das Persistenzformat und seine Validierung bleiben
 * vollstaendig in `localPreferences`; ArenaMetaController erhaelt nur diesen kleinen Vertrag.
 */
export function createArenaMetaProgressStore(): ArenaMetaProgressStore {
  return {
    getProgress: getStoredCoopDefenseProgress,
    restoreProgress: restoreStoredCoopDefenseProgress,
    getClassLoadout: getStoredCoopDefenseLoadout,
    setClassLoadoutSlot: setStoredCoopDefenseLoadoutSlot,
    setSharedLoadoutSlot: setStoredLoadoutSlot,
    switchClassLoadout: switchStoredCoopDefenseClassLoadout,
    setUpgradeProfile: setStoredCoopDefenseUpgradeProfile,
    resetUpgradeProfiles: resetStoredCoopDefenseUpgradeProfiles,
    setDebugProgress: setStoredCoopDefenseCheatProgress,
    resetCharacter: resetStoredCoopDefenseCharacter,
    addCoopDefenseXp: addStoredCoopDefenseXp,
    markCoopDefenseRoundProcessed: markStoredCoopDefenseRoundProcessed,
    markCoopDefenseBossMapCompleted: markStoredCoopDefenseBossMapCompleted,
    unlockCoopDefenseClassesAfterVictory: unlockStoredCoopDefenseClassesAfterVictory,
    unlockCoopDefenseMapAfterVictory: unlockStoredCoopDefenseMapAfterVictory,
    unlockPersistentBaseAfterVictory: unlockStoredPersistentBaseAfterVictory,
    unlockPersistentBaseAreaStageAfterVictory: unlockStoredPersistentBaseAreaStageAfterVictory,
    setPersistentBaseUnlocked: setStoredPersistentBaseUnlocked,
    setPersistentBaseAreaStage: setStoredPersistentBaseAreaStage,
    grantPersistentBaseRewards: grantStoredPersistentBaseRewards,
    setItemsUnlocked: setStoredCoopDefenseItemsUnlocked,
    unlockItemsAfterVictory: unlockStoredCoopDefenseItemsAfterVictory,
    markItemsSeen: markStoredCoopDefenseItemsSeen,
    equipItem: equipStoredCoopDefenseItem,
    unequipItem: unequipStoredCoopDefenseItem,
    salvageItem: salvageStoredCoopDefenseItem,
    setPendingItemReward: setStoredPendingCoopDefenseItemReward,
    claimPendingItemReward: claimStoredPendingCoopDefenseItemReward,
  };
}
