import type { ProjectileSpawnConfig, ProjectileRuntimeRecord } from '../types';
import type { ProjectileSpawnRequest } from './ProjectileSpawnRequest';

/**
 * Übersetzt einen aufgelösten Spawn-Auftrag in die Phaser-Physics-Binding-Payload.
 *
 * Die Abbildung ist eine reine Funktion ohne State, Identity oder Lifecycle. Sie lebt so lange,
 * Die Abbildung ist eine reine Funktion ohne State, Identity oder Lifecycle. Die vollständige
 * Provenance wird von der World-Runtime separat und unverändert in den Runtime-Record übergeben.
 */
export function toProjectileSpawnConfig(request: ProjectileSpawnRequest): ProjectileSpawnConfig {
  const { flight, provenance, interaction, presentation } = request;
  const directHit = interaction.directHit;
  const swarm = directHit?.plasmaSwarm;
  const lineage = provenance.lineage;
  const corridor = interaction.pathEffect?.awpCorridor;
  const miniRocket = flight.miniRocket;

  return {
    speed:  flight.speed,
    size:   flight.size,
    damage: directHit?.damage ?? 0,
    color:  presentation.color,
    lifetime:   flight.lifetimeMs,
    maxBounces: flight.maxBounces,
    isGrenade:  flight.isGrenade,
    collisionMode: flight.collisionMode,
    adrenalinGain: directHit?.adrenalinGain ?? 0,

    gameplayMuzzleOrigin: request.origin.gameplayMuzzleOrigin,
    visualMuzzleOrigin:   presentation.visualMuzzleOrigin,
    allowTeamDamage: provenance.allegiance.allowTeamDamage,
    sourceId:        provenance.weaponSourceId,
    sourceSlot:      provenance.sourceSlot,
    sourceTurretId:  provenance.sourceTurretId,
    reflected:       lineage?.reflected,
    ak47ShotId:      provenance.correlation?.ak47ShotId,

    ignoreBaseCollisions: flight.collisionFilter?.ignoreBaseCollisions,
    ignoreRockIndex:      flight.collisionFilter?.ignoreRockIndex,
    initialBounceCount:   flight.initialBounceCount,
    remainingRangePx:     flight.remainingRangePx,
    fuseTime:             flight.fuseTimeMs,
    homing:               flight.homing,
    piercesTargets:       flight.piercesTargets,
    penetrationCount:           flight.penetration?.count,
    penetrationDamageRetention: flight.penetration?.damageRetention,
    penetratesRocks:            flight.penetration?.penetratesRocks,
    velocityDecay:           flight.drag?.velocityDecayPerSec,
    frictionDelayMs:         flight.drag?.frictionDelayMs,
    airFrictionDecayPerSec:  flight.drag?.airFrictionDecayPerSec,
    bounceFrictionMultiplier: flight.drag?.bounceFrictionMultiplier,
    stopSpeedThreshold:      flight.drag?.stopSpeedThreshold,
    hitboxGrowRate: flight.hitboxGrowth?.growRatePerSec,
    hitboxMaxSize:  flight.hitboxGrowth?.maxSize,
    splitCount:  flight.split?.count,
    splitSpread: flight.split?.spread,
    splitFactor: flight.split?.speedFactor,
    splitHoming: flight.split?.homing,
    isFlame:       flight.isFlame,
    flamePiercing: flight.flamePiercing,
    isBfg:         flight.isBfg,
    miniRocketStageRangePx:   miniRocket?.stageRangePx,
    miniRocketReturnEnabled:  miniRocket?.returnEnabled,
    miniRocketReturnRangeBuffer: miniRocket?.returnRangeBuffer,
    miniRocketPickupRadius:   miniRocket?.pickupRadius,
    miniRocketPickupAdrenalineRefundFraction: miniRocket?.pickupAdrenalineRefundFraction,
    miniRocketPickupArmor:    miniRocket?.pickupArmor,
    miniRocketAdrenalineCostPaid: miniRocket?.adrenalineCostPaid,
    miniRocketSafetyLifetimeMs:   miniRocket?.safetyLifetimeMs,
    miniRocketCascadeDamageBonusPerExplosion: miniRocket?.cascadeDamageBonusPerExplosion,

    rockDamageMult:  directHit?.rockDamageMult,
    trainDamageMult: directHit?.trainDamageMult,
    baseDamageMult:  directHit?.baseDamageMult,
    hitSlowFraction:            directHit?.slowFraction,
    hitSlowDurationMs:          directHit?.slowDurationMs,
    hitVulnerabilityDurationMs: directHit?.vulnerabilityDurationMs,
    hitKnockback:               directHit?.knockback,
    hitKnockbackDurationMs:     directHit?.knockbackDurationMs,
    shotgunOriginX:        directHit?.shotgun?.originX,
    shotgunOriginY:        directHit?.shotgun?.originY,
    shotgunResolvedRange:  directHit?.shotgun?.resolvedRange,
    shotgunProximityMaxDamageBonus: directHit?.shotgun?.proximityMaxDamageBonus,
    shotgunSlowFraction:   directHit?.shotgun?.slowFraction,
    shotgunSlowDurationMs: directHit?.shotgun?.slowDurationMs,
    gaussChainRadius:       directHit?.gaussChain?.radius,
    gaussChainDamageFactor: directHit?.gaussChain?.damageFactor,
    ak47DamageMultiplier:    directHit?.ak47?.damageMultiplier,
    ak47FireSuperiorityShot: directHit?.ak47?.fireSuperiorityShot,
    plasmaSwarmEnabled:        swarm === undefined ? undefined : true,
    plasmaSwarmProjectileCount: swarm?.projectileCount,
    plasmaSwarmExplosionRadius: swarm?.explosionRadius,
    plasmaSwarmExplosionDamage: swarm?.explosionDamage,
    plasmaSwarmExplosionSlowFraction: swarm?.explosionSlowFraction,
    plasmaSwarmProjectile:     lineage?.plasmaSwarmChild,
    plasmaSwarmOriginEnemyId:  lineage?.plasmaSwarmOriginEnemyId,

    explosion:         interaction.explosion,
    enemyHitExplosion: interaction.enemyHitExplosion,
    multiExplosionCount:   interaction.multiExplosion?.count,
    multiExplosionCoastMs: interaction.multiExplosion?.coastMs,
    impactCloud:   interaction.impactCloud,
    grenadeEffect: interaction.grenadeEffect,
    burnDurationMs:            interaction.burn?.durationMs,
    burnDamagePerTick:         interaction.burn?.damagePerTick,
    projectileBurnVisualStyle: interaction.burn?.visualStyle,
    supplementalBurnOnHit:     interaction.burn?.supplemental,
    canReceiveFireImbue:       interaction.burn?.canReceiveFireImbue,
    fireTrail:               interaction.pathEffect?.fireTrail,
    pathEffectKind:          interaction.pathEffect?.kind,
    fireTrailHalfWidthCells: interaction.pathEffect?.fireTrailHalfWidthCells,
    awpCorridorHalfWidth:          corridor?.halfWidth,
    awpCorridorDamage:             corridor?.damage,
    awpCorridorDotDurationMs:      corridor?.dotDurationMs,
    awpCorridorDotTickIntervalMs:  corridor?.dotTickIntervalMs,
    awpCorridorKnockback:          corridor?.knockback,
    awpCorridorKnockbackDurationMs: corridor?.knockbackDurationMs,
    leafBlowerMinKnockback: interaction.impulse?.minKnockback,
    leafBlowerMaxKnockback: interaction.impulse?.maxKnockback,
    leafBlowerSelfPush:     interaction.impulse?.selfPush,
    leafBlowerDeflectsProjectiles: interaction.impulse?.deflectsProjectiles,
    energyInjectorPayload: interaction.support?.energyInjector,
    detonable:      interaction.detonable,
    detonator:      interaction.detonator,
    proximityPulse: interaction.proximityPulse,

    projectileStyle:       presentation.style,
    ownerColor:            presentation.ownerColor,
    projectileVisualScale: presentation.visualScale,
    bulletVisualPreset:    presentation.bulletPreset,
    grenadeVisualPreset:   presentation.grenadePreset,
    energyBallVariant:     presentation.energyBallVariant,
    sporeVisualVariant:    presentation.sporeVariant,
    smokeTrailColor:       presentation.smokeTrailColor,
    tracerConfig:          presentation.tracer,
    shotAudioKey:          presentation.shotAudioKey,
    suppressSpawnFx:       presentation.suppressSpawnFx,
  };
}

/**
 * Trägt die Restwirkung eines übernommenen Projectiles in seinen Nachfolger.
 *
 * Reflexion und Deflexion erzeugen ein neues Projectile; ohne diese Übertragung gingen Wolken,
 * Explosionen, Brand und Debuffs des Ursprungs still verloren.
 */
export function createInheritedProjectilePayload(
  record: ProjectileRuntimeRecord,
): Partial<ProjectileSpawnConfig> {
  return {
    explosion:            record.explosion,
    enemyHitExplosion:    record.enemyHitExplosion,
    impactCloud:          record.impactCloud,
    grenadeEffect:        record.grenadeEffect,
    burnDurationMs:       record.burnDurationMs,
    burnDamagePerTick:    record.burnDamagePerTick,
    projectileBurnVisualStyle: record.projectileBurnVisualStyle,
    supplementalBurnOnHit: record.supplementalBurnOnHit,
    supplementalBurnProvenance: record.supplementalBurnProvenance,
    canReceiveFireImbue:  record.canReceiveFireImbue,
    fireTrail:            record.fireTrail,
    pathEffectKind:       record.pathEffectKind,
    fireTrailHalfWidthCells: record.fireTrailHalfWidthCells,
    awpCorridorHalfWidth: record.awpCorridorHalfWidth,
    awpCorridorDamage:    record.awpCorridorDamage,
    awpCorridorDotDurationMs: record.awpCorridorDotDurationMs,
    awpCorridorDotTickIntervalMs: record.awpCorridorDotTickIntervalMs,
    awpCorridorKnockback: record.awpCorridorKnockback,
    awpCorridorKnockbackDurationMs: record.awpCorridorKnockbackDurationMs,
    detonable:            record.detonable,
    detonator:            record.detonator,
    proximityPulse:       record.proximityPulse,
    collisionMode:        record.collisionMode,
    isTranslocatorPuck:   record.isTranslocatorPuck,
    piercesTargets:       record.piercesTargets,
    penetrationCount:     record.penetrationRemaining,
    penetrationDamageRetention: record.penetrationDamageRetention,
    penetratesRocks:      record.penetratesRocks,
    isFlame:              record.isFlame,
    flamePiercing:        record.flamePierceHitIds !== undefined,
    isBfg:                record.isBfg,
    leafBlowerDeflectsProjectiles: record.leafBlowerDeflectsProjectiles,
    leafBlowerMinKnockback: record.leafBlowerMinKnockback,
    leafBlowerMaxKnockback: record.leafBlowerMaxKnockback,
    leafBlowerSelfPush:   record.leafBlowerSelfPush,
    gaussChainRadius:     record.gaussChainRadius,
    gaussChainDamageFactor: record.gaussChainDamageFactor,
    rockDamageMult:       record.rockDamageMult,
    trainDamageMult:      record.trainDamageMult,
    baseDamageMult:       record.baseDamageMult,
    hitSlowFraction:      record.hitSlowFraction,
    hitSlowDurationMs:    record.hitSlowDurationMs,
    hitVulnerabilityDurationMs: record.hitVulnerabilityDurationMs,
    hitKnockback:         record.hitKnockback,
    hitKnockbackDurationMs: record.hitKnockbackDurationMs,
  };
}
